package ludens.build.compose.language

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Scans Compose resource value directories and generates
 * a Kotlin source file listing all available languages.
 *
 * The generated file provides:
 * - `availableLanguages`: ordered list of language tags
 * - `languageLabel(tag)`: composable function that resolves the display label
 *   for a given language tag using Compose string resources.
 */
abstract class LanguageMetadataGenerationTask : DefaultTask() {

    /** Kotlin package used by the generated source file. */
    @get:Input
    abstract val packageName: Property<String>

    /** Top-level object name written to the generated Kotlin source. */
    @get:Input
    abstract val objectName: Property<String>

    /** Directory containing Compose `values` resource directories. */
    @get:InputDirectory
    abstract val resourceDir: DirectoryProperty

    /** Output file that will contain the generated Kotlin source. */
    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val dir = resourceDir.get().asFile
        val languages = discoverLanguages(dir)

        val content = buildString {
            appendLine("package ${packageName.get()}")
            appendLine()
            appendLine("import androidx.compose.runtime.Composable")
            appendLine("import ludens.composeapp.generated.resources.Res")
            appendLine("import ludens.composeapp.generated.resources.unknown_language")
            languages
                .map { it.labelResourceName }
                .distinct()
                .forEach { resourceName ->
                    appendLine("import ludens.composeapp.generated.resources.$resourceName")
                }
            appendLine("import org.jetbrains.compose.resources.StringResource")
            appendLine("import org.jetbrains.compose.resources.stringResource")
            appendLine()
            appendLine("// Autogenerated file. Do not edit manually.")
            appendLine("// Languages discovered from composeResources directories: ${languages.joinToString(", ") { it.tag }}")
            appendLine()
            appendLine("object ${objectName.get()} {")
            appendLine("    /** Ordered list of available language tags. */")
            appendLine("    val availableLanguages: List<String> = listOf(")
            languages.forEach { language ->
                appendLine("        \"${language.tag}\",")
            }
            appendLine("    )")
            appendLine()
            appendLine("    /** Resolves the [StringResource] for a language tag's display label. */")
            appendLine("    fun labelResource(tag: String): StringResource = when (tag) {")
            languages.forEach { language ->
                appendLine("        \"${language.tag}\" -> Res.string.${language.labelResourceName}")
            }
            appendLine("        else -> Res.string.unknown_language")
            appendLine("    }")
            appendLine()
            appendLine("    /**")
            appendLine("     * Returns the localized display label for the given language tag.")
            appendLine("     * Falls back to [stringResource] for unknown tags.")
            appendLine("     */")
            appendLine("    @Composable")
            appendLine("    fun languageLabel(tag: String): String {")
            appendLine("        return stringResource(labelResource(tag))")
            appendLine("    }")
            appendLine("}")
        }

        outputFile.get().asFile.apply {
            parentFile.mkdirs()
            writeText(content)
        }
    }

    /**
     * Discovers language tags by scanning Compose `values` directories.
     *
     * The default `values/` directory is treated as English (`en`). Locale
     * directories such as `values-es` and `values-pt-rBR` are converted to
     * BCP-47 tags (`es`, `pt-BR`) and mapped to safe resource names (`es`,
     * `pt_br`). Only languages whose display label resource exists in any
     * `strings.xml` file are included. Results are sorted for stable ordering.
     */
    private fun discoverLanguages(resourceDir: File): List<LanguageEntry> {
        val valuesDirs = resourceDir.listFiles { file ->
            file.isDirectory && (file.name == "values" || file.name.startsWith("values-"))
        } ?: emptyArray()

        // Collect all string names defined across all XML files
        val allStringNames = collectStringNames(resourceDir)

        return valuesDirs
            .mapNotNull { dir ->
                val language = languageEntryFor(dir)
                // Only include if a strings.xml exists in the directory
                // AND the display label is defined as a string resource somewhere
                if (!File(dir, "strings.xml").exists()) {
                    logger.warn("Language directory ${dir.name} has no strings.xml, skipping")
                    null
                } else if (language == null) {
                    logger.warn("Resource directory ${dir.name} does not map to a supported language tag, skipping")
                    null
                } else if (language.labelResourceName !in allStringNames) {
                    logger.warn("Language directory ${dir.name} found but label \"${language.labelResourceName}\" for tag \"${language.tag}\" is not defined as a string resource in any strings.xml")
                    null
                } else {
                    language
                }
            }
            .distinctBy { it.tag }
            .sortedBy { it.tag.lowercase() }
    }

    private fun languageEntryFor(dir: File): LanguageEntry? {
        if (dir.name == "values") {
            return LanguageEntry(tag = "en", labelResourceName = "en")
        }

        if (!dir.name.startsWith("values-")) {
            return null
        }

        val qualifier = dir.name.removePrefix("values-")
        val language = parseLanguageQualifier(qualifier) ?: return null
        return LanguageEntry(tag = language, labelResourceName = resourceNameFor(language))
    }

    private fun parseLanguageQualifier(qualifier: String): String? {
        val parts = qualifier.split('-')
        val language = parts.firstOrNull()
            ?.takeIf { it.matches(Regex("[a-z]{2,3}")) }
            ?: return null

        val region = parts
            .drop(1)
            .firstNotNullOfOrNull { part ->
                when {
                    part.matches(Regex("r[A-Z]{2}")) -> part.drop(1)
                    part.matches(Regex("[A-Z]{2}")) -> part
                    else -> null
                }
            }

        return if (region == null) language else "$language-$region"
    }

    private fun resourceNameFor(tag: String): String =
        tag.lowercase().replace('-', '_')

    /**
     * Collects all string `name` attributes from all `strings.xml` files in the
     * compose resources directory tree (including the default `values/`).
     */
    private fun collectStringNames(resourceDir: File): Set<String> {
        val names = mutableSetOf<String>()
        resourceDir.walkTopDown().forEach { file ->
            if (file.isFile && file.name == "strings.xml") {
                val content = file.readText()
                // Match <string name="...">
                val regex = Regex("""<string\s+name="([^"]+)"[^>]*>""")
                regex.findAll(content).forEach { match ->
                    names.add(match.groupValues[1])
                }
            }
        }
        return names
    }

    private data class LanguageEntry(
        val tag: String,
        val labelResourceName: String,
    )
}
