package ludens.build.compose.settings

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

abstract class SettingsPresetGenerationTask : DefaultTask() {

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val objectName: Property<String>

    @get:Input
    abstract val presetName: Property<String>

    @get:Input
    abstract val toolMuted: Property<Boolean>

    @get:Input
    abstract val toolShowFPS: Property<Boolean>

    @get:Input
    abstract val toolUseWebgl: Property<Boolean>

    @get:Input
    abstract val controlEnabled: Property<Boolean>

    @get:Input
    abstract val controlAlpha: Property<Float>

    @get:Input
    abstract val actionEnabled: Property<Boolean>

    @get:Input
    abstract val actionItems: Property<String>

    @get:Input
    abstract val systemTheme: Property<String>

    @get:Input
    abstract val systemLanguage: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val content = buildString {
            appendLine("package ${packageName.get()}")
            appendLine()
            appendLine("// Autogenerated file. Do not edit manually.")
            appendLine()
            appendLine("object ${objectName.get()} {")
            appendLine("    const val presetName: String = \"${escape(presetName.get())}\"")
            appendLine()
            appendLine("    object preset {")
            appendLine("        const val toolMuted: Boolean = ${toolMuted.get()}")
            appendLine("        const val toolShowFPS: Boolean = ${toolShowFPS.get()}")
            appendLine("        const val toolUseWebgl: Boolean = ${toolUseWebgl.get()}")
            appendLine("        const val controlEnabled: Boolean = ${controlEnabled.get()}")
            appendLine("        const val controlAlpha: Float = ${floatLiteral(controlAlpha.get())}")
            appendLine("        const val actionEnabled: Boolean = ${actionEnabled.get()}")
            appendLine("        const val actionItems: String = \"${escape(actionItems.get())}\"")
            appendLine("        const val systemTheme: String = \"${escape(systemTheme.get())}\"")
            appendLine("        const val systemLanguage: String = \"${escape(systemLanguage.get())}\"")
            appendLine("    }")
            appendLine("}")
        }

        outputFile.get().asFile.apply {
            parentFile.mkdirs()
            writeText(content)
        }
    }

    private fun floatLiteral(value: Float): String {
        val text = value.toString()
        return if (text.endsWith("f")) text else "${text}f"
    }

    private fun escape(value: String): String {
        return value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
    }
}
