package ludens.build.compose.resources

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*
import org.gradle.api.tasks.util.PatternSet

/**
 * Scans `composeResources/files` and generates a typed Kotlin object for file access.
 */
abstract class ComposeResourceFilesTask : DefaultTask() {

    /** Directory containing the compose resource files to scan. */
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val inputDir: DirectoryProperty

    /** Output Kotlin file containing the generated accessors. */
    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    /** Kotlin package used by the generated resource accessor object. */
    @get:Input
    abstract val packageName: Property<String>

    /** Include glob patterns applied to the input tree. */
    @get:Input
    @get:Optional
    abstract val includePatterns: ListProperty<String>

    /** Exclude glob patterns applied to the input tree. */
    @get:Input
    @get:Optional
    abstract val excludePatterns: ListProperty<String>

    /** Directory names excluded recursively from the generated tree. */
    @get:Input
    @get:Optional
    abstract val excludeDirs: ListProperty<String>

    @TaskAction
    fun generate() {
        val baseTree = inputDir.get().asFileTree

        val includes = includePatterns.getOrElse(emptyList())
        val excludes = excludePatterns.getOrElse(emptyList())
        val exDirs = excludeDirs.getOrElse(emptyList())

        val rootNode = Node("FileRes")

        val patterns = PatternSet()
        if (includes.isEmpty()) {
            patterns.include("**/*")
        } else {
            patterns.include(includes)
        }

        if (excludes.isNotEmpty()) patterns.exclude(excludes)

        exDirs.forEach { patterns.exclude("**/$it/**") }

        baseTree.matching(patterns).visit {
            if (!this.isDirectory) {
                addFileToTree(rootNode, this.relativePath.segments)
            }
        }

        val sb = StringBuilder()
        sb.appendLine("package ${packageName.get()}")
        sb.appendLine()
        sb.appendLine("// Autogenerated file. Do not edit manually.")
        sb.appendLine()
        sb.appendLine("object FileRes {")
        renderNode(sb, rootNode.children, indent = 1)
        sb.appendLine("}")

        outputFile.get().asFile.apply {
            parentFile.mkdirs()
            writeText(sb.toString())
        }
    }

    private data class Node(
        val name: String,
        val children: MutableList<Node> = mutableListOf(),
        var filePath: String? = null
    )

    private fun addFileToTree(root: Node, segments: Array<String>) {
        var current = root
        segments.forEachIndexed { index, segment ->
            val isLastSegment = index == segments.size - 1

            val nodeName = if (isLastSegment) {
                formatName(segment.substringBeforeLast("."))
            } else {
                formatName(segment)
            }

            var child = current.children.find { it.name == nodeName && it.filePath == null }

            if (child == null || isLastSegment) {
                child = Node(nodeName)
                current.children.add(child)
            }

            if (isLastSegment) {
                child.filePath = "files/${segments.joinToString("/")}"
            }
            current = child
        }
    }

    private fun renderNode(sb: StringBuilder, nodes: List<Node>, indent: Int) {
        val pad = "    ".repeat(indent)
        nodes.sortedWith(compareBy({ it.filePath != null }, { it.name })).forEach { node ->
            if (node.filePath != null) {
                sb.appendLine("""${pad}const val ${node.name} = "${node.filePath}"""")
            } else if (node.children.isNotEmpty()) {
                sb.appendLine("${pad}object ${node.name} {")
                renderNode(sb, node.children, indent + 1)
                sb.appendLine("$pad}")
            }
        }
    }

    private val kotlinKeywords = setOf(
        "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if",
        "in", "interface", "is", "null", "object", "package", "return", "super", "this",
        "throw", "true", "try", "typealias", "typeof", "val", "var", "when", "while"
    )

    private fun formatName(name: String): String {
        val sanitized = name.replace(Regex("[^a-zA-Z0-9_]"), "_")

        val withPrefix = if (sanitized.isEmpty() || sanitized.first().isDigit()) "_$sanitized" else sanitized

        return if (withPrefix in kotlinKeywords) "`$withPrefix`" else withPrefix
    }
}
